name: ranyun_sign
on: 
  workflow_dispatch:
  schedule: 
    - cron: '1 8 * * *'

jobs:
  rainyun_sign: 
    runs-on: ubuntu-latest
    steps: 
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r main/requirements.txt
      - name: sign the rainyun
        run: |
            cd main
            python main/main.py

    
